version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 60s
      timeout: 5s
      retries: 10

  goldmanager:
    image: docker.io/fg1212/goldmanager:0.3.0
    container_name: goldmanager
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      APP_DEFAULT_USER: admin
      APP_DEFAULT_PASSWORD: adminpassword!
      ALLOWEDORIGINS: http://localhost:9090
    ports:
      - "8080:8080"
    depends_on:
      - db

  goldmanagerui:
    image: docker.io/fg1212/goldmanager-ui:0.3.0
    container_name: goldmanager-ui
    restart: unless-stopped
    environment:
      VUE_APP_API_BASE_URL: http://localhost:8080
    ports:
      - "9090:8080"
    depends_on:
      - goldmanager

volumes:
  db-data:
